// Generated by text2c.pl. Do not edit directly.

const char default_glbuild_vs_glsl[] =
	"#glbuild(ES2) #version 100\n"
	"#glbuild(2)   #version 110\n"
	"#glbuild(3)   #version 140\n"
	"\n"
	"#ifdef GL_ES\n"
	"#elif __VERSION__ < 140\n"
	"#  define mediump\n"
	"#else\n"
	"#  define attribute in\n"
	"#  define varying out\n"
	"#endif\n"
	"\n"
	"attribute mediump vec2 a_vertex;\n"
	"attribute mediump vec2 a_texcoord;\n"
	"varying mediump vec2 v_texcoord;\n"
	"\n"
	"void main(void)\n"
	"{\n"
	"  v_texcoord = a_texcoord;\n"
	"  gl_Position = vec4(a_vertex, 0.0, 1.0);\n"
	"}\n"
;

const int default_glbuild_vs_glsl_size = 387;
